(use-modules (ice-9 hash-table))
(use-modules (ice-9 format))

(define (p_e_escape-string s)
    (define (p_e_escape-char c)
        (cond
            [(char=? c #\\) "\\\\"]
            [(char=? c #\") "\\\""]
            [(char=? c #\newline) "\\n"]
            [(char=? c #\tab) "\\t"]
            [else (string c)]))
    (apply string-append (map p_e_escape-char (string->list s))))

(define (p_e_bool)
    (lambda (b) 
        (unless (boolean? b) (error 'failed))
        (if b "true" "false")))

(define (p_e_int)
    (lambda (i) 
        (unless (integer? i) (error 'failed))
        (number->string i)))

(define (p_e_double)
    (lambda (d) 
        (unless (real? d) (error 'failed))
        (let* ([s0 (format #f "~,7f" d)]
            [s1 (substring s0 0 (- (string-length s0) 1))])
            (if (string=? s1 "-0.000000") "0.000000" s1))))

(define (p_e_string)
    (lambda (s) 
        (unless (string? s) (error 'failed))
        (string-append "\"" (p_e_escape-string s) "\"")))

(define (p_e_list f0)
    (lambda (lst) 
        (unless (list? lst) (error 'failed))
        (string-append "[" (string-join (map f0 lst) ", ") "]")))

(define (p_e_ulist f0)
    (lambda (lst) 
        (unless (list? lst) (error 'failed))
        (string-append "[" (string-join (sort (map f0 lst) string<?) ", ") "]")))

(define (p_e_idict f0)
    (let ([f1 (lambda (k v) (string-append ((p_e_int) k) "=>" (f0 v)))])
        (lambda (dct) 
            (unless (hash-table? dct) (error 'failed))
            (string-append "{" (string-join (sort (hash-map->list f1 dct) string<?) ", ") "}"))))

(define (p_e_sdict f0)
    (let ([f1 (lambda (k v) (string-append ((p_e_string) k) "=>" (f0 v)))])
        (lambda (dct) 
            (unless (hash-table? dct) (error 'failed))
            (string-append "{" (string-join (sort (hash-map->list f1 dct) string<?) ", ") "}"))))
    
(define (p_e_option f0)
    (lambda (opt) (if opt (f0 opt) "null")))

(let ([p_e_out (string-join (list
            ((p_e_bool) #t)
            ((p_e_bool) #f)
            ((p_e_int) 3)
            ((p_e_int) -107)
            ((p_e_double) 0.0)
            ((p_e_double) -0.0)
            ((p_e_double) 3.0)
            ((p_e_double) 31.4159265)
            ((p_e_double) 123456.789)
            ((p_e_string) "Hello, World!")
            ((p_e_string) "!@#$%^&*()[]{}<>:;,.'\"?|")
            ((p_e_string) "/\\\n\t")
            ((p_e_list (p_e_int)) (list))
            ((p_e_list (p_e_int)) (list 1 2 3))
            ((p_e_list (p_e_bool)) (list #t #f #t))
            ((p_e_list (p_e_string)) (list "apple" "banana" "cherry"))
            ((p_e_list (p_e_list (p_e_int))) (list))
            ((p_e_list (p_e_list (p_e_int))) (list (list 1 2 3) (list 4 5 6)))
            ((p_e_ulist (p_e_int)) (list 3 2 1))
            ((p_e_list (p_e_ulist (p_e_int))) (list (list 2 1 3) (list 6 5 4)))
            ((p_e_ulist (p_e_list (p_e_int))) (list (list 4 5 6) (list 1 2 3)))
            ((p_e_idict (p_e_int)) (alist->hash-table (list)))
            ((p_e_idict (p_e_string)) (alist->hash-table (list (cons 1 "one") (cons 2 "two"))))
            ((p_e_sdict (p_e_int)) (alist->hash-table (list (cons "one" 1) (cons "two" 2))))
            ((p_e_idict (p_e_list (p_e_int))) (alist->hash-table (list)))
            ((p_e_idict (p_e_list (p_e_int))) (alist->hash-table (list (cons 1 (list 1 2 3)) (cons 2 (list 4 5 6)))))
            ((p_e_sdict (p_e_list (p_e_int))) (alist->hash-table (list (cons "one" (list 1 2 3)) (cons "two" (list 4 5 6)))))
            ((p_e_list (p_e_idict (p_e_int))) (list (alist->hash-table (list (cons 1 2))) (alist->hash-table (list (cons 3 4)))))
            ((p_e_idict (p_e_idict (p_e_int))) (alist->hash-table (list (cons 1 (alist->hash-table (list (cons 2 3)))) (cons 4 (alist->hash-table (list (cons 5 6)))))))
            ((p_e_sdict (p_e_sdict (p_e_int))) (alist->hash-table (list (cons "one" (alist->hash-table (list (cons "two" 3)))) (cons "four" (alist->hash-table (list (cons "five" 6)))))))
            ((p_e_option (p_e_int)) 42)
            ((p_e_option (p_e_int)) #f)
            ((p_e_list (p_e_option (p_e_int))) (list 1 #f 3))
        ) "\n")])
    (let ((out-port (open-file "stringify.out" "w")))
        (display p_e_out out-port)
        (close-port out-port)))